FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app
COPY ./backend ./
RUN dotnet restore
RUN dotnet publish Qrss.API -o publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 as run
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Qrss.API.dll"]