version: "3.9"
services:
  image-service:
    build:
      context: .
      dockerfile: Dockerfile.ImageService
    volumes:
      - ./volumes/app/data:/app/data
  api:
    build:
      context: .
      dockerfile: Dockerfile.API
    volumes:
      - ./volumes/app/data:/app/data
    ports:
      - "8080:8080"
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
      - ./volumes/app/data:/usr/share/nginx/html/data
    depends_on:
      - api